# webapp/app.yaml
application: cloude-serverside
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: organiser.wsgi.application

libraries:
- name: django
  version: 1.5
