# webapp/app.yaml
application: 'comp3207-server'
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: organiser.wsgi.application

libraries:
- name: django
  version: 1.5

- name: MySQLdb
  version: "latest"
